### ISSUE TITLE
Unclear Table Data

### ISSUE THREAD

**Issue by kskilt** [learn-co-curriculum/phrg-SQL-bear-organizer-lab#2]
In this section:

"
column | type
-- | --
id | integer
name | text
age | integer
gender | char(1)(The choices would be "M" or "F")
color | text
temperament | text
alive | boolean
"
Having that note about M and F choices in parentheses is unclear directly following char(1) in the same style. I did not recognize that it was telling the user not telling the code to look for M and F only. As a coder, I thought this would be validating entry, as now I can input any character and be correct in the code.

**Comment by kskilt** [comment]
Also, in the lesson it says to make up data for the rest of the table, however Test number 15 is testing on specific number of brown bears. 

@garettarrowood

**Comment by garettarrowood** [comment]
Not sure what "test number 15" is. These tests aren't numbered. Make sure to include the precise test in future issues. -- It does look like one requires 8 bears, but that appears to be specified in the README [right here](https://github.com/learn-co-curriculum/phrg-SQL-bear-organizer-lab/blob/master/README.md#part-2-insert).

**Comment by garettarrowood** [comment]
README updated with valid SQL comment syntax in this commit - https://github.com/learn-co-curriculum/phrg-SQL-bear-organizer-lab/commit/84ec103db31a09b3050a509be2812ac2824f3487
